apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.data.name }}
  namespace: {{ .Values.data.namespace }}
  labels:
    app: {{ .Values.data.name }}
type: Opaque
stringData:
  {{- range $i, $e := until 3 }}
  {{ randAlpha 8 | lower }}: {{ randAlphaNum 32 | quote }}
  {{- end }}