apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
spec:
  generators:
    - list:
        elements:
          - cluster: dev-global-cluster-0
            url: https://kubernetes.default.svc # this should be changed to actual server url 
            valuesFile: 'https://raw.githubusercontent.com/KoRnZYSIEK/inp-spring-boot-api/main/values/dev-values.yaml'
          - cluster: prd-global-cluster-5
            url: https://kubernetes.default.svc # this should be changed to actual server url
            valuesFile: 'https://raw.githubusercontent.com/KoRnZYSIEK/inp-spring-boot-api/main/values/prd-values.yaml'
  template:
    metadata:
      name: '{{cluster}}-spring-boot-api'
    spec:
      project: default # this should be changed to project name
      source:
        repoURL: 'https://github.com/KoRnZYSIEK/inp-spring-boot-api'
        targetRevision: HEAD
        path: 'chart'
        helm:
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true